---
- name: Install Angular.js, Node.js and all that jazz
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - npm
    - nodejs
# - name: Install dsgrid
#   pip: name=dsgrid
